### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by matthewbaggett** [sotojuan/is-pokemon-go-up-cli#2]
geusebio@LincolnTux:~$ is-pokemon-go-up 

/usr/local/lib/node_modules/is-pokemon-go-up-cli/cli.js:4
const isPokemonGoUp = require('is-pokemon-go-up')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by radiovisual** [comment]
This [module doesn't seem to offer support for versions of Node less then v4](https://github.com/sotojuan/is-pokemon-go-up-cli/blob/master/.travis.yml#L3-L5), so if you upgrade your Node version to 4+, you shouldn't see this error.

**Comment by sotojuan** [comment]
Yep, I only supper Node 4 and above. Sorry!
